# Generated by Django 3.2.5 on 2021-07-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_mail', models.CharField(max_length=60)),
                ('user_cbal', models.IntegerField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
