# Generated by Django 3.2.5 on 2021-07-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_transfers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transfers',
            new_name='transfer',
        ),
    ]
